### ISSUE TITLE
Unable to use binding with Foreground property of DataGridTextColumn

### ISSUE THREAD

**Issue by Depechie** [MyToolkit/MyToolkit#38] opened 2015-12-24 10:59 UTC
I'm trying to use binding with a converter in a UWP app for the Forground property of DataGridTextColumn.
By using following code:
`Foreground="{Binding IsPrio, Converter={StaticResource BoolToColorConverter}}"`

I'm always getting following exception: WinRT information: Failed to assign to property 'MyToolkit.Controls.DataGridTextColumn.Foreground'

I've added a repro to test.
[TestMyToolkitGrid.zip](https://github.com/MyToolkit/MyToolkit/files/71667/TestMyToolkitGrid.zip)

**Comment by rsuter** [comment] 2015-12-26 15:51
The problem is that the properties on DataGridTextColumn are not dependency properties

**Comment by rsuter** [comment] 2015-12-26 16:04
Fixed in https://github.com/MyToolkit/MyToolkit/commit/7b5ef3ebb334fc500e8be2dd13c06be7264751c7

**Closed by rsuter** 2015-12-26 16:04 UTC

**Comment by Depechie** [comment] 2015-12-26 16:35
Ha great will try the fix when I have the time :)

**Comment by rsuter** [comment] 2015-12-26 18:57
Yes, please. But it is not available as nuget yet... Just download the sources and reference the necessary projects...
