### ISSUE TITLE
Issue with Vevo video

### ISSUE THREAD

**Issue by hesa2020** [MyToolkit/MyToolkit#24] opened 2015-11-10 18:47 UTC
Hello, since today the YouTube.GetVideoUriAsync
Get a url but when i browse it with chrome its a blank page and viewing the source return a blank file.

This seems to be happening with Vevo only.

Here is how i use the script: https://github.com/hesa2020/Hesa-Twitch-Bot/blob/master/HESA%20Twitch%20Bot/Managers/MusicManager.cs

Hopefully this will be fixed.
Thanks and i enjoy MyToolKit :D

**Comment by rsuter** [comment] 2015-11-12 08:29
Original issue: http://mytoolkit.codeplex.com/discussions/476808

**Comment by naweed** [comment] 2015-11-17 08:02
Same issue with Youtube videos as well.

Thanks. And love this great library.

**Comment by rsuter** [comment] 2015-11-17 18:53
Will be resolved tomorrow...

**Comment by naweed** [comment] 2015-11-18 04:34
Thank you buddy.

Just FYI, I love this toolkit. Amazing work.


On Tue, Nov 17, 2015 at 21:53 PM, Rico Suter <notifications@github.com>
wrote:

Will be resolved tomorrow...


—
Reply to this email directly or view it on GitHub
<https://github.com/MyToolkit/MyToolkit/issues/24#issuecomment-157469253>.










-- 
Sent from MetroMail

**Comment by rsuter** [comment] 2015-11-18 09:18
Fixed in v2.5.6, please check if it is working for you

**Closed** 2015-11-18 10:21 UTC
Labels: bug

**Comment by naweed** [comment] 2015-11-18 10:38
Will check tonight and update you. Thanks.

**Comment by naweed** [comment] 2015-11-18 17:35
Works like a charm :)

**Comment by naweed** [comment] 2015-11-24 10:20
Hi, the issue is back again since this morning. It is not working anymore.

**Comment by rsuter** [comment] 2015-11-24 18:08
Fixed again in v2.5.7

**Comment by naweed** [comment] 2015-11-25 02:57
Thanks. Is 2.5.7 code checked in? I think the code is still 2.5.6.

**Comment by rsuter** [comment] 2015-11-25 08:05
Its commited: https://github.com/MyToolkit/MyToolkit/commit/7d886a7d7a855954a325bbb4a0303f6a246e8ce0

**Comment by naweed** [comment] 2015-11-25 08:22
Thanks. Will check this tonight.

**Comment by naweed** [comment] 2015-11-25 16:03
Works fine now. Thanks once again.

**Comment by Sivze** [comment] 2015-12-19 21:08
Problem again with the Vevo Videos!

**Comment by naweed** [comment] 2015-12-20 04:15
YouTube videos also stopped working.
